/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MonstersIndexRouteImport } from './routes/monsters/index'
import { Route as MonstersIdRouteImport } from './routes/monsters/$id'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MonstersIndexRoute = MonstersIndexRouteImport.update({
  id: '/monsters/',
  path: '/monsters/',
  getParentRoute: () => rootRouteImport,
} as any)
const MonstersIdRoute = MonstersIdRouteImport.update({
  id: '/monsters/$id',
  path: '/monsters/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/favorites': typeof FavoritesRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/monsters/$id': typeof MonstersIdRoute
  '/monsters/': typeof MonstersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/favorites': typeof FavoritesRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/monsters/$id': typeof MonstersIdRoute
  '/monsters': typeof MonstersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/favorites': typeof FavoritesRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/monsters/$id': typeof MonstersIdRoute
  '/monsters/': typeof MonstersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/favorites'
    | '/login'
    | '/register'
    | '/monsters/$id'
    | '/monsters/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/favorites'
    | '/login'
    | '/register'
    | '/monsters/$id'
    | '/monsters'
  id:
    | '__root__'
    | '/'
    | '/favorites'
    | '/login'
    | '/register'
    | '/monsters/$id'
    | '/monsters/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FavoritesRoute: typeof FavoritesRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  MonstersIdRoute: typeof MonstersIdRoute
  MonstersIndexRoute: typeof MonstersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monsters/': {
      id: '/monsters/'
      path: '/monsters'
      fullPath: '/monsters/'
      preLoaderRoute: typeof MonstersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monsters/$id': {
      id: '/monsters/$id'
      path: '/monsters/$id'
      fullPath: '/monsters/$id'
      preLoaderRoute: typeof MonstersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FavoritesRoute: FavoritesRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  MonstersIdRoute: MonstersIdRoute,
  MonstersIndexRoute: MonstersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
