/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyTwoFactorRouteImport } from './routes/verify-2fa'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MonstersIndexRouteImport } from './routes/monsters/index'
import { Route as MonstersIdRouteImport } from './routes/monsters/$id'
import { Route as AccountSessionsRouteImport } from './routes/account/sessions'

const VerifyTwoFactorRoute = VerifyTwoFactorRouteImport.update({
  id: '/verify-2fa',
  path: '/verify-2fa',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MonstersIndexRoute = MonstersIndexRouteImport.update({
  id: '/monsters/',
  path: '/monsters/',
  getParentRoute: () => rootRouteImport,
} as any)
const MonstersIdRoute = MonstersIdRouteImport.update({
  id: '/monsters/$id',
  path: '/monsters/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountSessionsRoute = AccountSessionsRouteImport.update({
  id: '/account/sessions',
  path: '/account/sessions',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/favorites': typeof FavoritesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify-2fa': typeof VerifyTwoFactorRoute
  '/verify-email': typeof VerifyEmailRoute
  '/account/sessions': typeof AccountSessionsRoute
  '/monsters/$id': typeof MonstersIdRoute
  '/monsters/': typeof MonstersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/favorites': typeof FavoritesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify-2fa': typeof VerifyTwoFactorRoute
  '/verify-email': typeof VerifyEmailRoute
  '/account/sessions': typeof AccountSessionsRoute
  '/monsters/$id': typeof MonstersIdRoute
  '/monsters': typeof MonstersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/favorites': typeof FavoritesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify-2fa': typeof VerifyTwoFactorRoute
  '/verify-email': typeof VerifyEmailRoute
  '/account/sessions': typeof AccountSessionsRoute
  '/monsters/$id': typeof MonstersIdRoute
  '/monsters/': typeof MonstersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/favorites'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/verify-2fa'
    | '/verify-email'
    | '/account/sessions'
    | '/monsters/$id'
    | '/monsters/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/favorites'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/verify-2fa'
    | '/verify-email'
    | '/account/sessions'
    | '/monsters/$id'
    | '/monsters'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/favorites'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/verify-2fa'
    | '/verify-email'
    | '/account/sessions'
    | '/monsters/$id'
    | '/monsters/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  FavoritesRoute: typeof FavoritesRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  VerifyTwoFactorRoute: typeof VerifyTwoFactorRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  AccountSessionsRoute: typeof AccountSessionsRoute
  MonstersIdRoute: typeof MonstersIdRoute
  MonstersIndexRoute: typeof MonstersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-2fa': {
      id: '/verify-2fa'
      path: '/verify-2fa'
      fullPath: '/verify-2fa'
      preLoaderRoute: typeof VerifyTwoFactorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monsters/': {
      id: '/monsters/'
      path: '/monsters'
      fullPath: '/monsters/'
      preLoaderRoute: typeof MonstersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monsters/$id': {
      id: '/monsters/$id'
      path: '/monsters/$id'
      fullPath: '/monsters/$id'
      preLoaderRoute: typeof MonstersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/sessions': {
      id: '/account/sessions'
      path: '/account/sessions'
      fullPath: '/account/sessions'
      preLoaderRoute: typeof AccountSessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  FavoritesRoute: FavoritesRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  VerifyTwoFactorRoute: VerifyTwoFactorRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  AccountSessionsRoute: AccountSessionsRoute,
  MonstersIdRoute: MonstersIdRoute,
  MonstersIndexRoute: MonstersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
